on:
  push: # Run CI for all branches except GitHub merge queue tmp branches
    branches-ignore:
    - "gh-readonly-queue/**"
  pull_request: # Run CI for PRs on any branch
  merge_group: # Run CI for the GitHub merge queue
name: Build
env:
  RUSTFLAGS: '--deny warnings'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        TARGET:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - armv7-unknown-linux-gnueabihf
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          # - loongarch64-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          # - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu
          - s390x-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        include:
          # MSRV
          - rust: 1.85.0
            TARGET: x86_64-unknown-linux-gnu
          # Test nightly but don't fail
          - rust: nightly
            TARGET: x86_64-unknown-linux-gnu
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross --locked
      - name: Build
        run: cross build --target=${{ matrix.TARGET }}
      - name: Build all features
        run: cross build --target=${{ matrix.TARGET }} --all-features
      - name: Test
        run: cross test --target=${{ matrix.TARGET }}
      - name: Test all features
        run: cross test --target=${{ matrix.TARGET }} --all-features
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Ensure rustfmt is installed
        run: rustup component add rustfmt
      - name: Doc
        run: cargo doc
      - name: Formatting
        run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: '--allow warnings'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings